basic.showIcon(IconNames.Yes)
let strip = neopixel.create(DigitalPin.P2, 12, NeoPixelMode.RGB)
strip.setBrightness(30)
basic.showIcon(IconNames.Angry)
strip.show()
strip.clear()
let stem = strip.range(9, 2)
let left = strip.range(0, 3)
let center = strip.range(3, 3)
let right = strip.range(6, 3)
stem.showColor(neopixel.colors(NeoPixelColors.Green))
left.showColor(neopixel.rgb(255, 80, 0))
center.showColor(neopixel.rgb(255, 80, 0))
right.showColor(neopixel.rgb(255, 80, 0))
basic.forever(function () {
	
})
