basic.showIcon(IconNames.Yes)
let strip = neopixel.create(DigitalPin.P2, 12, NeoPixelMode.RGB)
strip.setBrightness(30)
basic.showIcon(IconNames.Angry)
strip.show()
strip.clear()
let stem = strip.range(9, 2)
let left = strip.range(0, 3)
let center = strip.range(3, 3)
let right = strip.range(6, 3)
stem.showColor(neopixel.colors(NeoPixelColors.Green))
let list = [80, 150, 80]
basic.forever(function () {
    basic.pause(100)
    left.clear()
    left.showColor(neopixel.rgb(255, list[0], 0))
    basic.pause(100)
    center.clear()
    center.showColor(neopixel.rgb(255, list[1], 0))
    basic.pause(100)
    right.clear()
    right.showColor(neopixel.rgb(255, list[2], 0))
    list.push(list.shift())
})
